# Generated by Django 4.0.3 on 2022-04-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_delete_curso_delete_entregable_delete_estudiantes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cantidad',
            field=models.IntegerField(default='0', verbose_name='cantidad'),
        ),
    ]
