# Generated by Django 4.0.4 on 2022-04-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_pedido_cantidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(max_length=50, verbose_name='fecha')),
                ('empresa', models.CharField(max_length=50, verbose_name='empresa')),
            ],
        ),
    ]
