# Generated by Django 4.0.4 on 2022-04-11 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_backup'),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='ruta',
            field=models.CharField(default='', max_length=50, verbose_name='ruta'),
        ),
    ]
