# Generated by Django 4.0.4 on 2022-04-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0005_backup_ruta'),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='estado',
            field=models.CharField(default='Revisar', max_length=50, verbose_name='estado'),
        ),
    ]
