# Generated by Django 4.0.4 on 2022-04-13 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0006_backup_estado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clientes',
        ),
    ]
