# Generated by Django 4.0.4 on 2022-04-13 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0007_delete_clientes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
