# Generated by Django 4.0.4 on 2022-04-13 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0008_delete_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulos',
            name='stock',
        ),
    ]
