# Generated by Django 4.0.4 on 2022-04-13 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0010_remove_articulos_descripcion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Articulos',
        ),
    ]
